### ISSUE TITLE
401 on Login-POST

### ISSUE THREAD

**Issue by kdotzlaw** [kdotzlaw/StudyBuddy#107] opened 2023-03-17 02:39 UTC
Login-POST response gives 401 error, indicating incorrect username/password. 
 File "C:\Users\andre\Documents\GitHub\StudyBuddy\backend\server.py", line 78, in request_loader
    username = request.get_json(force=True)['username']
KeyError: 'username'

**Comment by kdotzlaw** [comment] 2023-03-17 19:03
Also causes issues when adding requirements

**Comment by rdotzlaw** [comment] 2023-03-24 21:45
caused by missing 'username' key in JSON. this was fixed sometime between now and the creation of the issue, so marking as fixed

**Closed as completed by rdotzlaw** 2023-03-24 21:45 UTC
Labels: bug
